apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-java-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: tap-java-demo
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitops_server_address
    value: https://github.com/
  - name: gitops_repository_owner
    value: dbuchko
  - name: gitops_repository_name
    value: tap-run-gitops
  - name: gitops_ssh_secret
    value: git-ssh
  source:
    git:
      url: https://github.com/dbuchko/tap-java-demo
      ref:
        branch: main
